### PR TITLE
Fix nightly test failure

### LINKED ISSUE #4946: Connection Manager nightly test failure
```
2024-09-01T06:45:56.2519500Z       connection manager valid transition order:                                FAIL (8488.04s)
2024-09-01T06:45:56.2520325Z         *** Failed! Falsified (after 3 tests and 7272 shrinks):
2024-09-01T06:45:56.2522378Z         AbsBearerInfo {abiConnectionDelay = SmallDelay, abiInboundAttenuation = NoAttenuation FastSpeed, abiOutboundAttenuation = NoAttenuation FastSpeed, abiInboundWriteFailure = Nothing, abiOutboundWriteFailure = Just 0, abiAcceptFailure = Nothing, abiSDUSize = LargeSDU}
2024-09-01T06:45:56.2546933Z         DiffusionScript (SimArgs 1s 10) (Script ((fromList [],ShortDelay) :| [(fromList [],LongDelay)])) [(NodeArgs (-2) InitiatorAndResponderDiffusionMode GenesisMode (Just 269s) (fromList [(RelayAccessAddress "0:71:0:1:0:1:0:1" 65534,DoAdvertisePeer)]) (Script (DontUseBootstrapPeers :| [])) (TestAddress IPAddr (read "0:79::1:0:0") 3) PeerSharingDisabled [(HotValency {getHotValency = 1},WarmValency {getWarmValency = 1},fromList [(RelayAccessAddress "0:71:0:1:0:1:0:1" 65534,(DoAdvertisePeer,IsTrustable))])] ConsensusModePeerTargets {deadlineTargets = PeerSelectionTargets {targetNumberOfRootPeers = 4, targetNumberOfKnownPeers = 4, targetNumberOfEstablishedPeers = 3, targetNumberOfActivePeers = 2, targetNumberOfKnownBigLedgerPeers = 4, targetNumberOfEstablishedBigLedgerPeers = 1, targetNumberOfActiveBigLedgerPeers = 1}, syncTargets = PeerSelectionTargets {targetNumberOfRootPeers = 0, targetNumberOfKnownPeers = 4, targetNumberOfEstablishedPeers = 0, targetNumberOfActivePeers = 0, targetNumberOfKnownBigLedgerPeers = 4, targetNumberOfEstablishedBigLedgerPeers = 4, targetNumberOfActiveBigLedgerPeers = 3}} (Script (DNSTimeout {getDNSTimeout = 0.325s} :| [])) (Script (DNSLookupDelay {getDNSLookupDelay = 0.1s} :| [DNSLookupDelay {getDNSLookupDelay = 0.072s}])) (Nothing) False Script (FetchModeBulkSync :| [FetchModeBulkSync]) ============================================
2024-09-01T06:45:56.2560740Z         ,[JoinNetwork 0.5s]),(NodeArgs (0) InitiatorAndResponderDiffusionMode GenesisMode (Just 90s) (fromList []) (Script (DontUseBootstrapPeers :| [])) (TestAddress IPAddr (read "0:71:0:1:0:1:0:1") 65534) PeerSharingEnabled [(HotValency {getHotValency = 1},WarmValency {getWarmValency = 1},fromList [(RelayAccessAddress "0:79::1:0:0" 3,(DoNotAdvertisePeer,IsTrustable))])] ConsensusModePeerTargets {deadlineTargets = PeerSelectionTargets {targetNumberOfRootPeers = 1, targetNumberOfKnownPeers = 1, targetNumberOfEstablishedPeers = 1, targetNumberOfActivePeers = 1, targetNumberOfKnownBigLedgerPeers = 4, targetNumberOfEstablishedBigLedgerPeers = 3, targetNumberOfActiveBigLedgerPeers = 3}, syncTargets = PeerSelectionTargets {targetNumberOfRootPeers = 0, targetNumberOfKnownPeers = 1, targetNumberOfEstablishedPeers = 1, targetNumberOfActivePeers = 1, targetNumberOfKnownBigLedgerPeers = 4, targetNumberOfEstablishedBigLedgerPeers = 2, targetNumberOfActiveBigLedgerPeers = 2}} (Script (DNSTimeout {getDNSTimeout = 0.18s} :| [])) (Script (DNSLookupDelay {getDNSLookupDelay = 0.125s} :| [])) (Just (BlockNo 2)) False Script (FetchModeDeadline :| []) ============================================
2024-09-01T06:45:56.2568937Z         ,[JoinNetwork 1.484848484848s])]
2024-09-01T06:45:56.2574996Z         Schedule control: ControlAwait [ScheduleMod (RacyThreadId [3,1,3,1,2,3,2,1],7) ControlDefault [(RacyThreadId [3,1,3,1,2,3,2],32),(RacyThreadId [3,1,3,1,2,3,2],33),(RacyThreadId [2,1,3,1,4],8),(RacyThreadId [2,1,3,1,4],9),(RacyThreadId [2,1,3,1,4],10),(RacyThreadId [2,1,3,1,4],11),(RacyThreadId [2,1,3,1,4],12),(RacyThreadId [2,1,3,1,4,1],0),(RacyThreadId [2,1,3,1,4,1],1),(RacyThreadId [2,1,3,1,4,1],2),(RacyThreadId [2,1,3,1,4,1],3),(RacyThreadId [2,1,3,1,4,1],4),(RacyThreadId [2,1,3,1,4,1],5),(RacyThreadId [2,1,3,1,4,1],6),(RacyThreadId [2,1,3,1,4,1],7),(RacyThreadId [2,1,3,1,4,1],8),(RacyThreadId [2,1,3,1,4,1,1],0),(RacyThreadId [2,1,3,1,4,1,1],1),(RacyThreadId [2,1,3,1,4,1,1],2),(RacyThreadId [2,1,3,1,4,1,1],3),(RacyThreadId [2,1,3,1,4,1],9),(RacyThreadId [2,1,3,1,4,1],10),(RacyThreadId [2,1,3,1,4,1],11),(RacyThreadId [2,1,3,1,4,1],12),(RacyThreadId [2,1,3,1,4,1],13),(RacyThreadId [2,1,3,1,4,1],14),(RacyThreadId [2,1,3,1,4,1],15),(RacyThreadId [2,1,3,1,4],13),(RacyThreadId [2,1,3,1,4],14),(RacyThreadId [2,1,3,1,4],15),(RacyThreadId [2,1,3,1,4],16),(RacyThreadId [3,1,3,1,2,3,2],34)]]
2024-09-01T06:45:56.2581734Z         Thread {3,1,3,1,2,3,2,1} (out-conn-hndlr-TestAddress IPAddr (read "0:71:0:1:0:1:0:1") 65534-TestAddress IPAddr (read "0:79::1:0:0") 3) delayed at time Time 1.584848484848s
2024-09-01T06:45:56.2583234Z           until after:
2024-09-01T06:45:56.2583698Z             Thread {2,1,3,1,4}
2024-09-01T06:45:56.2584691Z             Thread {2,1,3,1,4} (accept-loop-TestAddress IPAddr (read "0:79::1:0:0") 3)
2024-09-01T06:45:56.2585566Z             Thread {2,1,3,1,4,1}
2024-09-01T06:45:56.2586093Z             Thread {2,1,3,1,4,1,1}
2024-09-01T06:45:56.2587556Z             Thread {2,1,3,1,4,1,1} (in-conn-hndlr-TestAddress IPAddr (read "0:79::1:0:0") 3-TestAddress IPAddr (read "0:71:0:1:0:1:0:1") 65534)
2024-09-01T06:45:56.2588796Z             Thread {3,1,3,1,2,3,2}
2024-09-01T06:45:56.2589384Z             Thread {3,1,3,1,2,3,2} (promoteColdPeer)
2024-09-01T06:45:56.2589996Z         
2024-09-01T06:45:56.2590359Z         
2024-09-01T06:45:56.2590756Z         Unexpected transition order!
2024-09-01T06:45:56.2591612Z         Went from: UnknownConnectionSt → ReservedOutboundSt
2024-09-01T06:45:56.2592500Z         to: UnnegotiatedSt Outbound → TerminatedSt
2024-09-01T06:45:56.2593692Z         Use --quickcheck-replay="(SMGen 12321819864453056501 17496576438499035377,2)" to reproduce.
2024-09-01T06:45:56.2595115Z         Use -p '/IOSimPOR.connection manager valid transition order/' to rerun this test only.
```
Full logs are available [here](https://productionresultssa11.blob.core.windows.net/actions-results/c00555ef-2d14-4161-8526-0580e2472b9c/workflow-job-run-c7c5e48c-161d-53e8-5c42-45caa4a2b2be/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-09-02T08%3A39%3A05Z&sig=lMG12WmbbNnQ%2FtzEZVC8FV8RXbvk95BC5ZeAi6PYoqQ%3D&ske=2024-09-02T17%3A57%3A58Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-09-02T05%3A57%3A58Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-05-04&sp=r&spr=https&sr=b&st=2024-09-02T08%3A29%3A00Z&sv=2024-05-04).

### PR DESCRIPTION
**Pull request by bolt12**
This commit adds tracing on connection manager TVar so that IOSimPOR doesn't find any wrong false positives.

Closes #4946

### CODE REVIEW

File: ouroboros-network-framework/testlib/Ouroboros/Network/ConnectionManager/Test/Utils.hs [hunk 1]
```diff
@@ -284,6 +284,14 @@ abstractStateIsFinalTransition :: Transition' AbstractState -> Bool
 abstractStateIsFinalTransition (Transition _ UnknownConnectionSt) = True
 abstractStateIsFinalTransition _                                  = False
 
+-- | This function is necessary to check tests that only read from the
+-- `traceTVar` logging output. These `traceTVar` logs do not transition to
+-- 'UnknownConnectionSt'.
```
Comment (coot) [inline ouroboros-network-framework/testlib/Ouroboros/Network/ConnectionManager/Test/Utils.hs:289]:
```suggestion
-- | This function is necessary to check tests that only read from the
-- `traceTVar` logging output. These `traceTVar` logs do not transition to
-- 'UnknownConnectionSt', since `UnknowConnectionSt` reflects the removal
-- of the `TVar` from the state map.
```

Comment (coot) [reply ouroboros-network-framework/testlib/Ouroboros/Network/ConnectionManager/Test/Utils.hs:289]: It's an interesting limitation of `traceTVar`.

We could trace the `any -> UnknownConnectionSt` transition using `traceM`.  Things cannot be reordered since this is always the last transition, so it should work in `IOSimPOR`.  The easiest way to do it would be to pass a `traceM` tracer which ignores all other transitions (so we don't get duplicate events).

File: ouroboros-network/sim-tests-lib/Test/Ouroboros/Network/Testnet.hs [hunk 2]
```diff
@@ -288,6 +294,155 @@ testWithIOSimPOR f traceNumber bi ds =
...
+                , (RacyThreadId [2,1,3,1,4], 16)
+                , (RacyThreadId [3,1,3,1,2,3,2], 34)
+                ]
+            ]
+      sim :: forall s. IOSim s Void
+      sim = do
+        exploreRaces
+        diffusionSimulation (toBearerInfo bi) ds iosimTracer
+  in exploreSimTrace (\a -> a { explorationReplay = Just s }) sim $ \_ ioSimTrace ->
+       prop_diffusion_cm_valid_transition_order ioSimTrace 10000
```
Comment (coot) [inline ouroboros-network/sim-tests-lib/Test/Ouroboros/Network/Testnet.hs:444]: nice

File: ouroboros-network-framework/src/Ouroboros/Network/ConnectionManager/Core.hs [hunk 3]
```diff
@@ -188,15 +189,54 @@ newFreshIdSupply _ = do
...
+      -- This is a false positive and we don't want that to happen.
+      --
+      -- The simplest way to do so is to leverage the `traceTVar` IOSim
+      -- capabilities. These trace messages won't be reordered by IOSimPOR
+      -- since these happen atomically in STM.
+      --
+      -- Another thing to note is that this trace differs from the IO one in
+      -- the fact that all connections terminate with a trace to
+      -- 'UnknownConnectionSt', since we can't do that here we limit ourselves
+      -- to 'TerminatedSt'.
```
[the remark this answers is not in the document]
Comment (bolt12) [reply ouroboros-network-framework/src/Ouroboros/Network/ConnectionManager/Core.hs:219]: You think so? I think it is in the right place, because a person reading the code might be wondering why this snippet of code is here and why we disregard the `UnknownConnectionSt` transition. I can put it in the testsuite as well

[the remark this answers is not in the document]
Comment (coot) [reply ouroboros-network-framework/src/Ouroboros/Network/ConnectionManager/Core.hs:220]: I think so.  This is only important in the test, not for IO.

**Review by coot — APPROVED** [review]
LGTM.  Just move the comment to tests.  If we'll have a problem again with the test the helpful info will be at right in front of us.
