### PR TITLE
churn no timeouts fix

### LINKED ISSUE #4922: Test failure for `IOSim.Churn.no timeouts`
```console
cabal run ouroboros-network:sim-tests -- --quickcheck-replay="(SMGen 6050026732172664616 1899791776656665259,21)" -p '/IOSim.Churn.no timeouts/'
```
on current `master` (283a9c87d0f076e24bb0689d9851c88913f0e056).

https://ci.iog.io/build/4954919/nixlog/1 / https://gist.github.com/amesgen/dbfd08695a32b2c66205ff4889afa632

### PR DESCRIPTION
**Pull request by crocodile-dentist**
# Description

This was a pain to find.

resolves #4922

# Checklist

### Quality
* [x] Commit sequence makes sense and have useful messages, see [ref][contrib#git-history].
* [ ] New tests are added and existing tests are updated.
* [ ] Self-reviewed the PR.

### Maintenance
* [ ] Linked an [issue][link-issue] or added the PR to the current sprint of [`ouroboros-network`][project] project.
* [ ] Added labels.
* [ ] Updated changelog files.
* [ ] The documentation has been properly updated, see [ref][contrib#documentation].

[project]: https://github.com/orgs/IntersectMBO/projects/5/views/1
[link-issue]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=
[contrib#git-history]: https://github.com/IntersectMBO/ouroboros-network/blob/master/CONTRIBUTING.md#git-history
[contrib#documentation]: https://github.com/IntersectMBO/ouroboros-network/blob/master/CONTRIBUTING.md#documentation

### CODE REVIEW

**Review by bolt12 — APPROVED** [review]

File: ouroboros-network/src/Ouroboros/Network/PeerSelection/Churn.hs [hunk 1]
```diff
@@ -347,10 +347,10 @@ peerChurnGovernor PeerChurnArgs {
     decreaseActiveBigLedgerPeers regime _ base targets =
       targets {
         targetNumberOfActiveBigLedgerPeers =
-          let praosSync = min 1 (targetNumberOfActiveBigLedgerPeers base)
+          let praosSyncTargets = min 1 (targetNumberOfActiveBigLedgerPeers base)
           in case regime of
-               ChurnBootstrapPraosSync -> praosSync
-               ChurnPraosSync -> praosSync
+               ChurnBootstrapPraosSync -> praosSyncTargets
+               ChurnPraosSync -> praosSyncTargets
```
Comment (coot) [inline ouroboros-network/src/Ouroboros/Network/PeerSelection/Churn.hs:353]: We use `praosSync` in other places. Maybe change it in other places as well?

File: ouroboros-network/src/Ouroboros/Network/PeerSelection/Churn.hs [hunk 2]
```diff
@@ -414,7 +414,7 @@ peerChurnGovernor PeerChurnArgs {
       -> HotValency
       -> PeerSelectionTargets
       -> ModifyPeerSelectionTargets
-    decreaseKnownBigLedgerPeers _ _ targets base =
```
Comment (coot) [inline ouroboros-network/src/Ouroboros/Network/PeerSelection/Churn.hs:417]: well spotted

**Review by coot — COMMENTED** [review]
Well done.

File: ouroboros-network/src/Ouroboros/Network/PeerSelection/Churn.hs (hunk 1 above)
Comment (crocodile-dentist) [reply ouroboros-network/src/Ouroboros/Network/PeerSelection/Churn.hs:353]: I think I renamed most of those to deadlineTargets as under Praos that's all we have and which is modified by stepping thru the churn loop. Here I decided to keep the praosSync prefix instead of renaming the let binding to deadlineTargets as maybe it would be slightly confusing.
